# SPDX-FileCopyrightText: Copyright 2025 The Open Source Project Security Baseline Authors
# SPDX-License-Identifier: Apache-2.0
---
name: Validate OSCAL Output

on:
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  verify:
    name: Setup and Generate
    runs-on: ubuntu-latest
    steps:
      - name: clone-baseline
        id: clone-baseline
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
                persist-credentials: false

      - name: clone-go-oscal
        id: clone-go-oscal
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
            repository: defenseunicorns/go-oscal
            path: .build/go-oscal/
            persist-credentials: false

      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        name: setup-go
        with:
          go-version: '1.24'
          check-latest: true
          cache: true

      - name: Setup Java # this is here because oscal-cli-action below needs a java runtime
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e
        id: setup-java
        with:
          distribution: temurin
          java-version: 17

      - run: |
          go build -C .build/go-oscal/ -o ${PWD}/go-oscal
          go build -C cmd/  -o ../baseline-compiler
          ./baseline-compiler oscal -b baseline > oscal-sample.json
          ./go-oscal validate --input-file oscal-sample.json 

      - name: Validate Catalog with oscal-club/metaschema CLI
        uses: oscal-club/oscal-cli-action@6a8b6368885714e46fa1d4a65a6ce665902e08b7 # v2.1.0
        with:
          args: catalog validate oscal-sample.json 

      - name: Validate Catalog with oscal-club/NIST CLI
        uses: oscal-club/oscal-cli-action@6a8b6368885714e46fa1d4a65a6ce665902e08b7 # v2.1.0
        with:
          oscalCliPackageUrl: https://repo1.maven.org/maven2/gov/nist/secauto/oscal/tools/oscal-cli/cli-core/1.0.3/cli-core-1.0.3-oscal-cli.tar.bz2
          args: catalog validate oscal-sample.json 
            
            
